//! Opt-in ML-KEM KeyGen trace capture.
//!
//! Trace records expose deterministic intermediate checkpoints for differential
//! testing. They do not imply FIPS 203 conformance and are compiled only when
//! the `std` feature is enabled.

use pqc_core::PqcResult;

use crate::fips_ntt;
use crate::kpke_keygen;
use crate::matrix;
use crate::poly::Poly;
use crate::symmetric;
use crate::MlKemParameterSet;

/// Deterministic checkpoints from one ML-KEM KeyGen execution.
#[derive(Clone, Eq, PartialEq)]
pub struct MlKemKeygenTrace<const EK_BYTES: usize, const DK_PKE_BYTES: usize> {
    /// Parameter set used by the execution.
    pub parameter_set: MlKemParameterSet,
    /// Key-generation input `d`.
    pub d: [u8; 32],
    /// Implicit-rejection input `z`.
    pub z: [u8; 32],
    /// Public matrix seed.
    pub rho: [u8; 32],
    /// Noise seed.
    pub sigma: [u8; 32],
    /// Digest of coefficient-domain matrix entry `A[0][0]`.
    pub matrix_00_digest: [u8; 32],
    /// Digest of coefficient-domain secret polynomial `s[0]`.
    pub secret_0_digest: [u8; 32],
    /// Digest of coefficient-domain error polynomial `e[0]`.
    pub error_0_digest: [u8; 32],
    /// Digest of NTT-domain secret polynomial `s_hat[0]`.
    pub secret_hat_0_digest: [u8; 32],
    /// Digest of NTT-domain error polynomial `e_hat[0]`.
    pub error_hat_0_digest: [u8; 32],
    /// Digest of coefficient-domain public polynomial `t[0]`.
    pub public_0_digest: [u8; 32],
    /// Digest of NTT-domain public polynomial `t_hat[0]`.
    pub public_hat_0_digest: [u8; 32],
    /// Encoded encapsulation key generated by the current implementation.
    pub encapsulation_key: [u8; EK_BYTES],
    /// Encoded CPA secret-key component generated by the current implementation.
    pub cpa_secret_key: [u8; DK_PKE_BYTES],
}

impl<const EK_BYTES: usize, const DK_PKE_BYTES: usize> core::fmt::Debug
    for MlKemKeygenTrace<EK_BYTES, DK_PKE_BYTES>
{
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter
            .debug_struct("MlKemKeygenTrace")
            .field("parameter_set", &self.parameter_set)
            .field("encapsulation_key_bytes", &EK_BYTES)
            .field("cpa_secret_key_bytes", &DK_PKE_BYTES)
            .field("sensitive_fields", &"<redacted>")
            .finish()
    }
}

/// Capture ML-KEM-512 KeyGen checkpoints.
pub fn trace_ml_kem_512_keygen(
    d: &[u8; 32],
    z: &[u8; 32],
) -> PqcResult<MlKemKeygenTrace<800, 768>> {
    trace_keygen::<800, 768>(MlKemParameterSet::MlKem512, d, z)
}

/// Capture ML-KEM-768 KeyGen checkpoints.
pub fn trace_ml_kem_768_keygen(
    d: &[u8; 32],
    z: &[u8; 32],
) -> PqcResult<MlKemKeygenTrace<1184, 1152>> {
    trace_keygen::<1184, 1152>(MlKemParameterSet::MlKem768, d, z)
}

/// Capture ML-KEM-1024 KeyGen checkpoints.
pub fn trace_ml_kem_1024_keygen(
    d: &[u8; 32],
    z: &[u8; 32],
) -> PqcResult<MlKemKeygenTrace<1568, 1536>> {
    trace_keygen::<1568, 1536>(MlKemParameterSet::MlKem1024, d, z)
}

fn trace_keygen<const EK_BYTES: usize, const DK_PKE_BYTES: usize>(
    parameter_set: MlKemParameterSet,
    d: &[u8; 32],
    z: &[u8; 32],
) -> PqcResult<MlKemKeygenTrace<EK_BYTES, DK_PKE_BYTES>> {
    let material = kpke_keygen::expand_keygen_seed_for_parameter_set(parameter_set, d);
    let matrix = matrix::expand_matrix(parameter_set.k(), &material.rho, false);
    let secret = kpke_keygen::sample_noise_vector(parameter_set, &material.sigma, 0);
    let error =
        kpke_keygen::sample_noise_vector(parameter_set, &material.sigma, parameter_set.k() as u8);
    let public = kpke_keygen::compute_public_vector(parameter_set.k(), &matrix, &secret, &error);
    let keypair = kpke_keygen::keygen_from_seed::<EK_BYTES, DK_PKE_BYTES>(parameter_set, d)?;

    let secret_hat = fips_ntt::ntt(&secret.as_slice()[0]);
    let error_hat = fips_ntt::ntt(&error.as_slice()[0]);
    let public_hat = fips_ntt::ntt(&public.as_slice()[0]);

    Ok(MlKemKeygenTrace {
        parameter_set,
        d: *d,
        z: *z,
        rho: material.rho,
        sigma: material.sigma,
        matrix_00_digest: digest_poly(matrix.get(0, 0)),
        secret_0_digest: digest_poly(&secret.as_slice()[0]),
        error_0_digest: digest_poly(&error.as_slice()[0]),
        secret_hat_0_digest: digest_ntt(&secret_hat),
        error_hat_0_digest: digest_ntt(&error_hat),
        public_0_digest: digest_poly(&public.as_slice()[0]),
        public_hat_0_digest: digest_ntt(&public_hat),
        encapsulation_key: keypair.public_key,
        cpa_secret_key: keypair.secret_key,
    })
}

fn digest_poly(poly: &Poly) -> [u8; 32] {
    symmetric::h(&poly.encode_12())
}

fn digest_ntt(poly: &fips_ntt::FipsNttPoly) -> [u8; 32] {
    digest_poly(&Poly::from_coefficients(*poly.coefficients()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trace_is_deterministic() {
        let d = [0x11u8; 32];
        let z = [0x22u8; 32];

        assert_eq!(
            trace_ml_kem_512_keygen(&d, &z).unwrap(),
            trace_ml_kem_512_keygen(&d, &z).unwrap(),
        );
    }

    #[test]
    fn trace_records_parameter_specific_seed_expansion() {
        let d = [0x33u8; 32];
        let z = [0x44u8; 32];

        let k512 = trace_ml_kem_512_keygen(&d, &z).unwrap();
        let k768 = trace_ml_kem_768_keygen(&d, &z).unwrap();

        assert_ne!(k512.rho, k768.rho);
        assert_ne!(k512.sigma, k768.sigma);
    }
}
