[package]
name = "pqc-rs-test-harness"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[features]
default = ["std"]
std = ["pqc-core/std", "pqc-ml-kem/std"]
alloc = ["pqc-core/alloc", "pqc-ml-kem/alloc"]
acvp = ["pqc-core/acvp"]
bench = ["pqc-core/bench"]

[dependencies]
pqc-core = { package = "pqc-rs-core", workspace = true, features = ["std"] }
pqc-ml-kem = { package = "pqc-rs-ml-kem", path = "../pqc-ml-kem", version = "0.4.0-rc.1", features = ["std"] }
rand_core = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pqc-hpke = { package = "pqc-rs-hpke", path = "../pqc-hpke", version = "0.4.0-rc.1" }
pqc-ml-dsa = { package = "pqc-rs-ml-dsa", version = "0.4.0-rc.1", path = "../pqc-ml-dsa" }
sha3 = { workspace = true }

[lib]
name = "pqc_test_harness"
