[package]
name = "pqc-rs-test-harness"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[features]
default = ["std"]
std = ["pqc-core/std", "pqc-ml-kem/std"]
alloc = ["pqc-core/alloc", "pqc-ml-kem/alloc"]
acvp = ["pqc-core/acvp"]
bench = ["pqc-core/bench"]

[dependencies]
pqc-core = { workspace = true, features = ["std"] }
pqc-ml-kem = { workspace = true, features = ["std"] }
rand_core = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pqc-hpke = { workspace = true }
pqc-ml-dsa = { workspace = true, features = ["internal-api"] }
pqc-slh-dsa = { package = "pqc-rs-slh-dsa", version = "0.4.0", path = "../pqc-slh-dsa" }
sha3 = { workspace = true }

[lib]
name = "pqc_test_harness"
