[package]
name = "pqc-rs-hpke"
version = "0.4.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "HPKE with ML-KEM and post-quantum/traditional hybrid key encapsulation for PQC-rs."
readme = "README.md"
categories = ["cryptography"]
keywords = ["post-quantum", "cryptography", "hpke", "ml-kem", "rust"]

[features]
default = ["std"]
std = ["pqc-core/std"]
alloc = ["pqc-core/alloc"]
acvp = ["pqc-core/acvp"]
bench = ["pqc-core/bench"]

[dependencies]
pqc-core = { workspace = true }
rand_core = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
pqc-ml-kem = { workspace = true }
sha3 = { workspace = true }
aes-gcm = { workspace = true }
chacha20poly1305 = { workspace = true }
zeroize = { workspace = true }
x25519-dalek = { workspace = true }
p256 = { workspace = true }
p384 = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "hpke"
harness = false

[[bench]]
name = "hybrid_hpke"
harness = false

[[bench]]
name = "composition"
harness = false

[lib]
name = "pqc_hpke"
