[package]
name = "pqc-rs-slh-dsa"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[features]
default = ["std"]
std = ["pqc-core/std"]
alloc = ["pqc-core/alloc"]
acvp = ["pqc-core/acvp"]
bench = ["pqc-core/bench"]

[dependencies]
pqc-core = { package = "pqc-rs-core", workspace = true }
rand_core = { workspace = true }

[lib]
name = "pqc_slh_dsa"
