[package]
name = "pqc-rs-hybrid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Support for post-quantum and traditional hybrid cryptographic composition in PQC-rs."
readme = "README.md"
categories = ["cryptography"]
keywords = ["post-quantum", "cryptography", "hybrid", "pqc", "rust"]

[features]
default = ["std"]
std = ["pqc-core/std"]
alloc = ["pqc-core/alloc"]
acvp = ["pqc-core/acvp"]
bench = ["pqc-core/bench"]

[dependencies]
pqc-core = { workspace = true }
rand_core = { workspace = true }

[lib]
name = "pqc_hybrid"
