#!/usr/bin/env python3
"""Generate or check the B1.3.1 public API inventory."""
from __future__ import annotations
import argparse, re, sys
import tomllib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/api/API_INVENTORY.md'
def workspace_crates():
    manifest = tomllib.loads((ROOT/'Cargo.toml').read_text())
    members = manifest.get('workspace', {}).get('members', [])
    crates = []
    for member in members:
        src = ROOT/member/'src'
        if src.is_dir():
            crates.append(src)
    return sorted(crates)


CRATES=workspace_crates()
PAT=re.compile(r'^\s*pub\s+(?:unsafe\s+)?(struct|enum|trait|fn|type|const|static|mod)\s+([A-Za-z_][A-Za-z0-9_]*)', re.M)
REEXPORT=re.compile(r'^\s*pub\s+use\s+([^;]+);', re.M)
MLDSA_PAT=re.compile(
    r'^\s*pub\s+(?:const\s+)?(?:unsafe\s+)?'
    r'(struct|enum|trait|fn|type|const|static)\s+'
    r'([A-Za-z_][A-Za-z0-9_]*)',
    re.M,
)

def classify(crate, kind, name, path):
    if name.endswith('Placeholder'):
        return 'Deprecated debt'

    if kind == 'mod' and path.name == 'lib.rs':
        if name == 'internal_api':
            return 'Internal unstable'
        if crate == 'pqc-test-harness':
            return 'Tooling'

    if crate == 'pqc-hpke' and name.startswith('setup_') and '_with_suite' in name:
        return 'Preferred'
    if crate == 'pqc-hpke' and name.startswith('setup_'):
        return 'Stable compatibility'

    return 'Stable'

def collect_mldsa(src):
    crate=src.parent.name
    rows=[]
    lib=src/'lib.rs'
    rel=lib.relative_to(ROOT).as_posix()
    for module in ('api','error','params'):
        rows.append((crate,'mod',module,rel,'Stable'))
    text=lib.read_text(errors='ignore')
    for item in REEXPORT.findall(text):
        rows.append((crate,'re-export',item.strip().replace('\n',' '),rel,'Stable'))

    for name in ('api.rs','error.rs','params.rs'):
        path=src/name
        rel=path.relative_to(ROOT).as_posix()
        for kind,item in MLDSA_PAT.findall(path.read_text(errors='ignore')):
            rows.append((crate,kind,item,rel,'Stable'))

    path=src/'hash_mldsa.rs'
    rel=path.relative_to(ROOT).as_posix()
    rows.append((crate,'enum','PreHashAlgorithm',rel,'Stable'))
    return rows



def collect_slhdsa(src):
    crate=src.parent.name
    rows=[]
    lib=src/'lib.rs'
    rel=lib.relative_to(ROOT).as_posix()

    for module in ('api','error','params'):
        rows.append((crate,'mod',module,rel,'Stable'))

    lib_text=lib.read_text(errors='ignore')
    for item in REEXPORT.findall(lib_text):
        rows.append((crate,'re-export',item.strip().replace('\n',' '),rel,'Stable'))

    internal_api_decl=re.compile(
        r'(?ms)^\s*#\[cfg\(feature = "internal-api"\)\]\s*'
        r'(?:#\[[^\n]*\]\s*)*'
        r'(?P<decl>'
        r'pub\s+(?:const\s+)?(?:unsafe\s+)?'
        r'(?:struct|enum|trait|fn|type|const|static)\s+'
        r'[A-Za-z_][A-Za-z0-9_]*'
        r')'
    )

    for name in ('api.rs','error.rs','params.rs'):
        source_path=src/name
        rel=source_path.relative_to(ROOT).as_posix()
        source=source_path.read_text(errors='ignore')

        hidden_names={
            m.group('decl').split('(')[0].split()[-1]
            for m in internal_api_decl.finditer(source)
        }

        for kind,item in MLDSA_PAT.findall(source):
            if item in hidden_names:
                continue
            rows.append((crate,kind,item,rel,'Stable'))

    prehash=src/'hash_slhdsa.rs'
    rel=prehash.relative_to(ROOT).as_posix()
    rows.append((crate,'enum','SlhDsaPreHash',rel,'Stable'))

    return rows

def collect():
    rows=[]
    for src in CRATES:
        crate=src.parent.name
        if crate=='pqc-ml-dsa':
            rows.extend(collect_mldsa(src))
            continue
        if crate=='pqc-slh-dsa':
            rows.extend(collect_slhdsa(src))
            continue
        for p in sorted(src.rglob('*.rs')):
            if '/bin/' in p.as_posix() or '#[cfg(test)]' in p.read_text(errors='ignore')[:200]: pass
            text=p.read_text(errors='ignore')
            rel=p.relative_to(ROOT).as_posix()
            for kind,name in PAT.findall(text):
                rows.append((crate,kind,name,rel,classify(crate,kind,name,p)))
            if p.name=='lib.rs':
                for item in REEXPORT.findall(text): rows.append((crate,'re-export',item.strip().replace('\n',' '),rel,'Stable'))
    return rows

def render(rows):
    exposed=sum(1 for r in rows if r[4]=='Exposed implementation')
    internal=sum(1 for r in rows if r[4]=='Internal unstable')
    tooling=sum(1 for r in rows if r[4]=='Tooling')
    debt=sum(1 for r in rows if r[4]=='Deprecated debt')
    preferred=sum(1 for r in rows if r[4]=='Preferred')
    lines=['# Public API Inventory','','Generated by `cargo xtask api-review`. Do not edit manually.','',
    '## Review summary','',f'- Public declarations and re-exports inventoried: **{len(rows)}**',f'- Preferred suite-first HPKE entry points: **{preferred}**',f'- Exposed implementation modules retained for compatibility: **{exposed}**',f'- Feature-gated internal/unstable modules: **{internal}**',f'- Public tooling modules outside the cryptographic compatibility boundary: **{tooling}**',f'- Public placeholder types recorded as compatibility debt: **{debt}**','',
    '## Stability classes','',
    '- **Preferred**: recommended entry point for new integrations.','- **Stable**: supported public contract.','- **Stable compatibility**: retained to avoid source breakage; not preferred for new code.','- **Internal unstable**: feature-gated engineering or assurance surface explicitly excluded from the supported compatibility contract.','- **Tooling**: repository validation/test infrastructure outside the PQC-rs cryptographic compatibility boundary.','- **Exposed implementation**: public implementation detail that remains compatibility debt.','- **Deprecated debt**: historical placeholder retained until a breaking release.','',
    '| Crate | Kind | Item | Source | Classification |','|---|---|---|---|---|']
    for row in rows: lines.append('| ' + ' | '.join(x.replace('|','\\|') for x in row) + ' |')
    lines += ['','## B1.3.1 decisions','',
    '1. `HpkeSuite` is the preferred ciphersuite boundary. Suite-first setup functions preserve validation through context construction.',
    '2. Identifier-based HPKE setup functions remain available as source-compatible wrappers.',
    '3. Implementation and assurance surfaces are encapsulated before 1.0; feature-gated `internal-api` interfaces are explicitly excluded from the supported compatibility contract.',
    '4. Placeholder-only crates and APIs are excluded from the 1.0 compatibility boundary until they provide supported functionality.',
    '5. New public APIs must be documented and must be added to this inventory before merge.','']
    return '\n'.join(lines)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args()
    content=render(collect())
    if a.check:
        if not OUT.exists() or OUT.read_text()!=content:
            print('public API inventory is stale; run cargo xtask api-review',file=sys.stderr); return 1
        print('B1.3.1 API inventory: pass'); return 0
    OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(content); print(f'wrote {OUT.relative_to(ROOT)}'); return 0
if __name__=='__main__': raise SystemExit(main())
