#!/usr/bin/env python3
"""Generate or check the B1.3.1 public API inventory."""
from __future__ import annotations
import argparse, re, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/api/API_INVENTORY.md'
CRATES=sorted((ROOT/'crates').glob('*/src'))
PAT=re.compile(r'^\s*pub\s+(?:unsafe\s+)?(struct|enum|trait|fn|type|const|static|mod)\s+([A-Za-z_][A-Za-z0-9_]*)', re.M)
REEXPORT=re.compile(r'^\s*pub\s+use\s+([^;]+);', re.M)

def classify(crate, kind, name, path):
    if name.endswith('Placeholder'): return 'Deprecated debt'
    if crate=='pqc-hpke' and name.startswith('setup_') and '_with_suite' in name: return 'Preferred'
    if crate=='pqc-hpke' and name.startswith('setup_'): return 'Stable compatibility'
    if kind=='mod' and path.name=='lib.rs' and name not in {'error','identifiers','context','setup','suite'}: return 'Exposed implementation'
    return 'Stable'

def collect():
    rows=[]
    for src in CRATES:
        crate=src.parent.name
        for p in sorted(src.rglob('*.rs')):
            if '/bin/' in p.as_posix() or '#[cfg(test)]' in p.read_text(errors='ignore')[:200]: pass
            text=p.read_text(errors='ignore')
            rel=p.relative_to(ROOT).as_posix()
            for kind,name in PAT.findall(text):
                rows.append((crate,kind,name,rel,classify(crate,kind,name,p)))
            if p.name=='lib.rs':
                for item in REEXPORT.findall(text): rows.append((crate,'re-export',item.strip().replace('\n',' '),rel,'Stable'))
    return rows

def render(rows):
    exposed=sum(1 for r in rows if r[4]=='Exposed implementation')
    debt=sum(1 for r in rows if r[4]=='Deprecated debt')
    preferred=sum(1 for r in rows if r[4]=='Preferred')
    lines=['# Public API Inventory','','Generated by `cargo xtask api-review`. Do not edit manually.','',
    '## Review summary','',f'- Public declarations and re-exports inventoried: **{len(rows)}**',f'- Preferred suite-first HPKE entry points: **{preferred}**',f'- Exposed implementation modules retained for compatibility: **{exposed}**',f'- Public placeholder types recorded as compatibility debt: **{debt}**','',
    '## Stability classes','',
    '- **Preferred**: recommended entry point for new integrations.','- **Stable**: supported public contract.','- **Stable compatibility**: retained to avoid source breakage; not preferred for new code.','- **Exposed implementation**: currently public but targeted for encapsulation in a future major release.','- **Deprecated debt**: historical placeholder retained until a breaking release.','',
    '| Crate | Kind | Item | Source | Classification |','|---|---|---|---|---|']
    for row in rows: lines.append('| ' + ' | '.join(x.replace('|','\\|') for x in row) + ' |')
    lines += ['','## B1.3.1 decisions','',
    '1. `HpkeSuite` is the preferred ciphersuite boundary. Suite-first setup functions preserve validation through context construction.',
    '2. Identifier-based HPKE setup functions remain available as source-compatible wrappers.',
    '3. Existing implementation modules are not hidden in this milestone because doing so would be a broad breaking change.',
    '4. Placeholder types are documented as compatibility debt and should be removed only in a planned major release.',
    '5. New public APIs must be documented and must be added to this inventory before merge.','']
    return '\n'.join(lines)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args()
    content=render(collect())
    if a.check:
        if not OUT.exists() or OUT.read_text()!=content:
            print('public API inventory is stale; run cargo xtask api-review',file=sys.stderr); return 1
        print('B1.3.1 API inventory: pass'); return 0
    OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(content); print(f'wrote {OUT.relative_to(ROOT)}'); return 0
if __name__=='__main__': raise SystemExit(main())
