#!/usr/bin/env python3
"""Generate and enforce the B1.3.2 secret-lifetime policy."""
from __future__ import annotations
import argparse, re, sys, tomllib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
POLICY=ROOT/'compliance/secret-policy.toml'
INVENTORY=ROOT/'docs/security/SECRET_INVENTORY.md'
AUDIT=ROOT/'docs/security/ZEROIZATION_AUDIT.md'

REQUIRED={'id','type','source','representation','zeroization','clone_policy','copy_policy','debug_policy','exposure_policy','rationale'}

def load():
    data=tomllib.loads(POLICY.read_text())
    rows=data.get('secret',[])
    errors=[]
    ids=set()
    for i,row in enumerate(rows):
        missing=REQUIRED-set(row)
        if missing: errors.append(f'entry {i} missing {sorted(missing)}')
        if row.get('id') in ids: errors.append(f'duplicate id {row.get("id")}')
        ids.add(row.get('id'))
        p=ROOT/row.get('source','')
        if not p.is_file(): errors.append(f'{row.get("id")}: missing source {row.get("source")}')
        elif row.get('type','').split('::')[-1].split('<')[0].split()[0] not in p.read_text(errors='ignore'):
            # Aggregated policies intentionally describe fields rather than one exact declaration.
            if ' fields' not in row.get('type','') and ' material' not in row.get('type',''):
                errors.append(f'{row.get("id")}: type marker not found in source')
        if row.get('copy_policy')!='forbidden': errors.append(f'{row.get("id")}: Copy must be forbidden')
        if row.get('clone_policy','').startswith('allowed') and not row.get('rationale','').strip():
            errors.append(f'{row.get("id")}: allowed Clone requires rationale')
    return data,rows,errors

def icon(v): return {'forbidden':'No','redacted':'Redacted'}.get(v,v)

def inventory(data,rows):
    lines=['# Secret Inventory','','Generated by `cargo xtask zeroization-audit`. Do not edit manually.','',
           f'Policy schema: **{data["metadata"]["schema_version"]}**  ',f'Milestone: **{data["metadata"]["milestone"]}**  ',
           f'Classified secret lifetimes: **{len(rows)}**','','| ID | Type or boundary | Source | Representation | Zeroization | Clone | Copy | Debug | Exposure |',
           '|---|---|---|---|---|---|---|---|---|']
    for r in rows:
        vals=[r['id'],f'`{r["type"]}`',f'`{r["source"]}`',r['representation'],r['zeroization'],icon(r['clone_policy']),icon(r['copy_policy']),icon(r['debug_policy']),r['exposure_policy']]
        lines.append('| '+' | '.join(v.replace('|','\\|') for v in vals)+' |')
    lines += ['','## Interpretation','',
      '- `allowed-compatibility` records an existing public contract; it is not the preferred policy for new secret types.',
      '- `allowed-reviewed` requires an explicit algorithmic rationale and treats every clone as a distinct secret lifetime.',
      '- Explicit byte extraction or encoding transfers zeroization responsibility to the caller.',
      '- A clean policy check establishes implementation discipline; it does not prove removal of compiler, register, swap, or crash-dump copies.','']
    return '\n'.join(lines)

def audit(data,rows):
    allowed=[r for r in rows if r['clone_policy'].startswith('allowed')]
    lines=['# Zeroization and Secret-Lifetime Audit','','Generated by `cargo xtask zeroization-audit`. Do not edit manually.','',
      '## Decision','','**PASS with documented compatibility exceptions.** All classified owned secret containers have an explicit destruction policy; `Copy` is forbidden throughout the policy.','',
      '## Audit invariants','',
      '1. Every policy entry resolves to a repository source file.',
      '2. Owned secret containers use `ZeroizeOnDrop` or an explicit zeroizing `Drop` implementation.',
      '3. `Copy` is forbidden for secret-bearing types.',
      '4. Any permitted `Clone` has an explicit rationale and creates an additional secret lifetime.',
      '5. Diagnostic formatting is either absent or redacted.',
      '6. Secret extraction is explicit; extracted arrays or vectors become caller-managed secret copies.','',
      '## Reviewed exceptions','']
    for r in allowed:
        lines += [f'### `{r["type"]}`','',f'- Policy: `{r["clone_policy"]}`',f'- Rationale: {r["rationale"]}','']
    lines += ['## Residual limitations','',
      '- Zeroization cannot guarantee erasure of compiler-generated temporaries, registers, operating-system swap, crash dumps, or prior allocator copies.',
      '- Third-party cryptographic key types are governed by their dependency contracts and require separate version-specific review.',
      '- Test-vector and ACVP harness structures may intentionally retain secret material for validation and are outside the production-type policy boundary.',
      '- Constant-time behavior is a separate B1.3.3 review and is not implied by this audit.','',
      '## Maintenance rule','',
      'Any new owned secret-bearing type must be added to `compliance/secret-policy.toml`. CI runs `cargo xtask zeroization-audit --check`; generated documents must remain synchronized with the policy.','']
    return '\n'.join(lines)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args()
    data,rows,errors=load()
    expected={INVENTORY:inventory(data,rows),AUDIT:audit(data,rows)}
    if errors:
        for e in errors: print(f'error: {e}',file=sys.stderr)
        return 1
    if a.check:
        stale=[p for p,c in expected.items() if not p.exists() or p.read_text()!=c]
        if stale:
            for p in stale: print(f'stale: {p.relative_to(ROOT)}',file=sys.stderr)
            print('run cargo xtask zeroization-audit',file=sys.stderr); return 1
        print(f'B1.3.2 zeroization audit: pass ({len(rows)} classified lifetimes)'); return 0
    for p,c in expected.items(): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(c)
    print('wrote docs/security/SECRET_INVENTORY.md')
    print('wrote docs/security/ZEROIZATION_AUDIT.md')
    return 0
if __name__=='__main__': raise SystemExit(main())
