name: Dynamic analysis

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "41 8 * * 4"

permissions:
  contents: read

jobs:
  miri:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri, rust-src
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly miri setup
      - run: ./scripts/run-miri.sh

  address-sanitizer:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: ./scripts/run-address-sanitizer.sh

  undefined-behavior-sanitizer:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: ./scripts/run-undefined-behavior-sanitizer.sh
